export const LANG_STRINGS = {
  en: {
    pickLang:    'Choose your language',
    pickSub:     'We\'ll remember your preference on this device.',
    btn:         'Continue',
    chatGreet:   'Hi! 👋 Welcome to Digital Safalta.',
    chatSub:     'Tell me what you\'re looking for and I\'ll point you in the right direction.',
    chatStart:   'What can we help you with?',
    services:    ['Website Design', 'Google / Meta Ads', 'SEO', 'Social Media Management', 'I need multiple services'],
    ws1q: 'Do you already have a website?',
    ws1a: ['Yes, I want to redesign it', 'I have a domain but no website', 'Starting completely from scratch'],
    ws2q: 'What\'s your timeline?',
    ws2a: ['As soon as possible', 'Within 1 month', 'I\'m just exploring'],
    ws3q: 'What\'s your budget for the website?',
    ws3a: ['Under ₹15,000', '₹15,000 (standard package)', '₹15,000–₹30,000', '₹30,000+'],
    ad1q: 'Which platform are you interested in?',
    ad1a: ['Google Ads', 'Meta Ads (Facebook/Instagram)', 'Both'],
    ad2q: 'What\'s your monthly ad budget (total spend)?',
    ad2a: ['Under ₹10,000/month', '₹10,000–₹25,000/month', '₹25,000+/month', 'Not sure yet'],
    ad3q: 'Are you currently running any ads?',
    ad3a: ['Yes, but not getting results', 'Never run ads before', 'Ran before, stopped'],
    seo1q: 'Do you have a website we can optimise?',
    seo1a: ['Yes', 'No — I need one first'],
    seo2q: 'Are you ranking for any keywords currently?',
    seo2a: ['Yes, but want to improve', 'No ranking at all', 'I don\'t know'],
    seo3q: 'What\'s your SEO timeline?',
    seo3a: ['Want results in 3–6 months', 'Long-term investment (6–12 months)', 'Just exploring'],
    sm1q: 'Which platforms do you want managed?',
    sm1a: ['Instagram', 'Facebook', 'Both Instagram & Facebook', 'LinkedIn'],
    sm2q: 'Do you have photos or content ready?',
    sm2a: ['Yes, I have plenty', 'Partially ready', 'No, need help with content too'],
    sm3q: 'How many posts per month are you thinking?',
    sm3a: ['12 posts/month', '20 posts/month', 'Custom — let\'s discuss'],
    multiMsg: 'Great! Combining services is the best way to grow. Let\'s talk and build a plan tailored to your business.',
    endMsg:  'Thanks! Here\'s how you can reach us — choose what works best for you:',
    form:    'Fill the Contact Form',
    wa:      'Chat on WhatsApp',
    call:    'Call Us',
    email:   'Email Us',
    emailCopied: 'Copied!',
    restart: 'Start over',
  },
  hi: {
    pickLang:   'अपनी भाषा चुनें',
    pickSub:    'हम इस डिवाइस पर आपकी प्राथमिकता याद रखेंगे।',
    btn:        'जारी रखें',
    chatGreet:  'नमस्ते! 👋 Digital Safalta में आपका स्वागत है।',
    chatSub:    'बताइए आप क्या ढूंढ रहे हैं — हम सही दिशा में मदद करेंगे।',
    chatStart:  'हम आपकी किस तरह मदद कर सकते हैं?',
    services:   ['वेबसाइट डिज़ाइन', 'Google / Meta Ads', 'SEO', 'सोशल मीडिया मैनेजमेंट', 'मुझे कई सेवाएं चाहिए'],
    ws1q: 'क्या आपके पास पहले से वेबसाइट है?',
    ws1a: ['हां, मैं इसे redesign करना चाहता हूं', 'Domain है, वेबसाइट नहीं', 'बिल्कुल नई शुरुआत'],
    ws2q: 'आपकी समयसीमा क्या है?',
    ws2a: ['जितनी जल्दी हो सके', '1 महीने के भीतर', 'सिर्फ जानकारी ले रहा हूं'],
    ws3q: 'वेबसाइट के लिए आपका बजट क्या है?',
    ws3a: ['₹15,000 से कम', '₹15,000 (मानक पैकेज)', '₹15,000–₹30,000', '₹30,000+'],
    ad1q: 'आप किस प्लेटफॉर्म में रुचि रखते हैं?',
    ad1a: ['Google Ads', 'Meta Ads (Facebook/Instagram)', 'दोनों'],
    ad2q: 'आपका मासिक ad बजट क्या है?',
    ad2a: ['₹10,000/माह से कम', '₹10,000–₹25,000/माह', '₹25,000+/माह', 'अभी तय नहीं'],
    ad3q: 'क्या आप अभी ads चला रहे हैं?',
    ad3a: ['हां, पर परिणाम नहीं मिल रहे', 'पहले कभी ads नहीं चलाए', 'पहले चलाए थे, बंद कर दिए'],
    seo1q: 'क्या आपके पास optimize करने के लिए वेबसाइट है?',
    seo1a: ['हां', 'नहीं — पहले वेबसाइट चाहिए'],
    seo2q: 'क्या आप अभी किसी keyword पर rank कर रहे हैं?',
    seo2a: ['हां, पर सुधार चाहता हूं', 'बिल्कुल नहीं', 'मुझे नहीं पता'],
    seo3q: 'SEO के लिए आपकी समयसीमा क्या है?',
    seo3a: ['3–6 महीने में परिणाम', '6–12 महीने का दीर्घकालिक निवेश', 'सिर्फ जानकारी ले रहा हूं'],
    sm1q: 'आप कौन से प्लेटफॉर्म मैनेज करवाना चाहते हैं?',
    sm1a: ['Instagram', 'Facebook', 'Instagram & Facebook दोनों', 'LinkedIn'],
    sm2q: 'क्या आपके पास फोटो या कंटेंट तैयार है?',
    sm2a: ['हां, बहुत है', 'कुछ है', 'नहीं, कंटेंट में भी मदद चाहिए'],
    sm3q: 'प्रति माह कितने posts चाहिए?',
    sm3a: ['12 posts/माह', '20 posts/माह', 'Custom — बात करते हैं'],
    multiMsg: 'बढ़िया! कई सेवाएं मिलाकर काम करना सबसे असरदार होता है। चलिए बात करते हैं और आपके बिज़नेस के लिए एक plan बनाते हैं।',
    endMsg:  'धन्यवाद! आप इस तरह हमसे संपर्क कर सकते हैं:',
    form:    'Contact Form भरें',
    wa:      'WhatsApp पर Chat करें',
    call:    'Call करें',
    email:   'Email करें',
    emailCopied: 'कॉपी हो गया!',
    restart: 'फिर से शुरू करें',
  },
  mr: {
    pickLang:   'तुमची भाषा निवडा',
    pickSub:    'आम्ही या डिव्हाइसवर तुमची प्राधान्यता लक्षात ठेवू.',
    btn:        'पुढे चला',
    chatGreet:  'नमस्कार! 👋 Digital Safalta मध्ये आपले स्वागत आहे।',
    chatSub:    'तुम्हाला काय हवे आहे ते सांगा — आम्ही योग्य दिशेने मदत करू.',
    chatStart:  'आम्ही तुम्हाला कशात मदत करू शकतो?',
    services:   ['वेबसाइट डिझाइन', 'Google / Meta Ads', 'SEO', 'सोशल मीडिया व्यवस्थापन', 'मला अनेक सेवा हव्यात'],
    ws1q: 'तुमच्याकडे आधीच वेबसाइट आहे का?',
    ws1a: ['हो, मला ती redesign करायची आहे', 'Domain आहे, वेबसाइट नाही', 'अगदी नव्याने सुरुवात'],
    ws2q: 'तुमची वेळमर्यादा काय आहे?',
    ws2a: ['शक्य तितक्या लवकर', '1 महिन्याच्या आत', 'फक्त माहिती घेत आहे'],
    ws3q: 'वेबसाइटसाठी तुमचे बजेट किती आहे?',
    ws3a: ['₹15,000 पेक्षा कमी', '₹15,000 (मानक पॅकेज)', '₹15,000–₹30,000', '₹30,000+'],
    ad1q: 'तुम्हाला कोणत्या प्लॅटफॉर्ममध्ये रस आहे?',
    ad1a: ['Google Ads', 'Meta Ads (Facebook/Instagram)', 'दोन्ही'],
    ad2q: 'तुमचे मासिक ad बजेट किती आहे?',
    ad2a: ['₹10,000/महिना पेक्षा कमी', '₹10,000–₹25,000/महिना', '₹25,000+/महिना', 'अजून ठरवले नाही'],
    ad3q: 'तुम्ही सध्या ads चालवत आहात का?',
    ad3a: ['हो, पण परिणाम मिळत नाहीत', 'आधी कधीच ads चालवले नाहीत', 'आधी चालवले होते, बंद केले'],
    seo1q: 'तुमच्याकडे optimize करण्यासाठी वेबसाइट आहे का?',
    seo1a: ['हो', 'नाही — आधी वेबसाइट हवी'],
    seo2q: 'तुम्ही सध्या कोणत्याही keyword वर rank करत आहात का?',
    seo2a: ['हो, पण सुधारणा हवी', 'अजिबात नाही', 'मला माहीत नाही'],
    seo3q: 'SEO साठी तुमची वेळमर्यादा काय आहे?',
    seo3a: ['3–6 महिन्यांत परिणाम', '6–12 महिन्यांची दीर्घकालीन गुंतवणूक', 'फक्त माहिती घेत आहे'],
    sm1q: 'तुम्हाला कोणते प्लॅटफॉर्म व्यवस्थापित करायचे आहेत?',
    sm1a: ['Instagram', 'Facebook', 'Instagram & Facebook दोन्ही', 'LinkedIn'],
    sm2q: 'तुमच्याकडे फोटो किंवा कंटेंट तयार आहे का?',
    sm2a: ['हो, भरपूर आहे', 'काही तयार आहे', 'नाही, कंटेंटमध्येही मदत हवी'],
    sm3q: 'महिन्याला किती posts हव्यात?',
    sm3a: ['12 posts/महिना', '20 posts/महिना', 'Custom — बोलूया'],
    multiMsg: 'छान! अनेक सेवा एकत्र वापरणे सर्वात प्रभावी आहे. चला बोलूया आणि तुमच्या व्यवसायासाठी एक योजना बनवूया.',
    endMsg:  'धन्यवाद! तुम्ही आम्हाला यापैकी कोणत्याही प्रकारे संपर्क करू शकता:',
    form:    'Contact Form भरा',
    wa:      'WhatsApp वर Chat करा',
    call:    'Call करा',
    email:   'Email करा',
    emailCopied: 'कॉपी झाले!',
    restart: 'पुन्हा सुरू करा',
  },
};
